[package]
name = "water2"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
ggez = "0.9.3"
image = "0.24.7"
itertools = "0.11.0"
rand = "0.8.5"
thiserror = "1.0.47"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

